# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cbbaf0e54d121a5ec65dc4dd9cc02d77aa458d4497de59a1319bf23d6fe39007f4c37dac1eb9249403aa513b908d70447b29f7167295ffed52a6401a8a69331

test:
  secret_key_base: 443e17ac4dac1e3433700f1ef28b9e021784e15d3f9dcce0e479dd6b7d7f845ae30574403d696af41ba2c018ede459d80b01c8d2355120fd1d19d9d37902987c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
